# 1. Các phép toán trên vector và ma trận.

## (a) Độ dài của vector:

### 1.1 Length of a vector

- **Vector**: $\mathbf{v} = [v_1, v_2, ..., v_n]^T$
- **Length of a vector**: $\|\mathbf{v}\| = \sqrt{v_1^2 + v_2^2 + ... + v_n^2}$

Hãy hoàn thiện hàm `compute_vector_length()` để tính độ dài của vector sử dụng thư viện numpy:



In [1]:
import numpy as np

def compute_vector_length(vector):
    # *********** Your code here ***********
    v = np.array(vector)
    len_of_vector = np.linalg.norm(v)

    return len_of_vector

In [2]:
v = [1, 2, 3]
compute_vector_length(v)

3.7416573867739413

## (b) Phép tích vô hướng:

### 1.2 Dot product

- **Vector**: $\mathbf{v} = \begin{bmatrix} v_1 \\ v_2 \\ \vdots \\ v_n \end{bmatrix}$, $\mathbf{u} = \begin{bmatrix} u_1 \\ u_2 \\ \vdots \\ u_n \end{bmatrix}$

- **Dot Product**: $\mathbf{v} \cdot \mathbf{u} = v_1 \cdot u_1 + v_2 \cdot u_2 + \ldots + v_n \cdot u_n$

Hãy hoàn thiện hàm `compute_dot_product()` sử dụng thư viện numpy:


In [3]:
def compute_dot_product(vector1, vector2):
    # *********** Your code here ***********
    v1 = np.array(vector1)
    v2 = np.array(vector2)
    result = np.dot(v1, v2)

    return result

In [4]:
v1 = [1, 2, 3]
v2 = [4, 5, 6]
compute_dot_product(v1, v2)

32

## (c) Nhân vector với ma trận:

### 1.3 Multiplying a vector by a matrix

- **Matrix**: $\mathbf{A} = \begin{bmatrix}
a_{11} & \cdots & a_{1n} \\
\vdots & \ddots & \vdots \\
a_{m1} & \cdots & a_{mn}
\end{bmatrix}$, $\mathbf{A} \in \mathbb{R}^{m \times n}$

- **Vector**: $\mathbf{v} = \begin{bmatrix}
v_1 \\
v_2 \\
\vdots \\
v_n
\end{bmatrix}$, $\mathbf{v} \in \mathbb{R}^n$

- **Result**: $\mathbf{c} = \mathbf{A} \mathbf{v} = \begin{bmatrix}
a_{11} \cdot v_1 + \ldots + a_{1n} \cdot v_n \\
\vdots \\
a_{m1} \cdot v_1 + \ldots + a_{mn} \cdot v_n
\end{bmatrix}$, $\mathbf{c} \in \mathbb{R}^m$

Hãy hoàn thiện hàm `matrix_multi_vector()` sử dụng thư viện numpy:

In [5]:
def matrix_multi_vector(matrix, vector):
    # *********** Your code here ***********
    A = np.array(matrix)
    v = np.array(vector)
    result = np.dot(A, v)

    return result

In [6]:
A = [[1, 2], [3, 4], [5, 6]]
v = [7, 8]
matrix_multi_vector(A, v)

array([23, 53, 83])

## (d) Nhân ma trận với ma trận:

### 1.4 Multiplying a matrix by a matrix

- **Matrix A**: $\mathbf{A} = \begin{bmatrix}
a_{11} & \cdots & a_{1n} \\
\vdots & \ddots & \vdots \\
a_{m1} & \cdots & a_{mn}
\end{bmatrix}$, $\mathbf{A} \in \mathbb{R}^{m \times n}$

- **Matrix B**: $\mathbf{B} = \begin{bmatrix}
b_{11} & \cdots & b_{1k} \\
\vdots & \ddots & \vdots \\
b_{n1} & \cdots & b_{nk}
\end{bmatrix}$, $\mathbf{B} \in \mathbb{R}^{n \times k}$

- **Result**: $\mathbf{C} = \mathbf{A} \mathbf{B} = \begin{bmatrix}
a_{11} \cdot b_{11} + \ldots + a_{1n} \cdot b_{n1} & \cdots & a_{11} \cdot b_{1k} + \ldots + a_{1n} \cdot b_{nk} \\
\vdots & \ddots & \vdots \\
a_{m1} \cdot b_{11} + \ldots + a_{mn} \cdot b_{n1} & \cdots & a_{m1} \cdot b_{1k} + \ldots + a_{mn} \cdot b_{nk}
\end{bmatrix}$, $\mathbf{C} \in \mathbb{R}^{m \times k}$

Hãy hoàn thiện hàm `matrix_multi_matrix()` sử dụng thư viện numpy:

In [7]:
import numpy as np

def matrix_multi_matrix(matrix1, matrix2):
  A = np.array(matrix1)
  B = np.array(matrix2)
  result = np.matmul(A, B)

  return result

In [8]:
A = [[1, 2], [3, 4], [5, 6]]
B = [[7, 8, 9], [10, 11, 12]]
matrix_multi_matrix(A, B)

array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])

## (e) Ma trận nghịch đảo:

### 1.5 Matrix inverse

- **Matrix A**: $\mathbf{A} = \begin{bmatrix}
a & b \\
c & d
\end{bmatrix}$, $\mathbf{A} \in \mathbb{R}^{2 \times 2}$

- **Determinant of A** $\in \mathbb{R}^{2 \times 2}$: $\text{det}(\mathbf{A}) = ad - bc$

- **Inverse Matrix**: $\mathbf{A}^{-1} = \frac{1}{\text{det}(\mathbf{A})} \begin{bmatrix}
d & -b \\
-c & a
\end{bmatrix}$, nếu $\text{det}(\mathbf{A}) \neq 0$ thì $\mathbf{A}$ là khả nghịch

Cho trước $\mathbf{A} = \begin{bmatrix}
-2 & 6 \\
8 & -4
\end{bmatrix}$, tìm $\mathbf{A}^{-1}$.

Dựa vào công thức ở trên, hãy hoàn thiện hàm `inverse_matrix()` sử dụng thư viện numpy:

In [9]:
import numpy as np

def inverse_matrix(matrix):
  A = np.array(matrix)
  det = np.linalg.det(A)
  if det == 0:
    return None
  else:
    result = np.linalg.inv(A)
  return result

In [10]:
A = [[-2, 6], [8, -4]]
inverse_matrix(A)

array([[0.1 , 0.15],
       [0.2 , 0.05]])

## 2. Eigenvector và eigenvalues:

### 2.1 Eigenvector and eigenvalue

- **Matrix A** $\in \mathbb{R}^{n \times n}$, $\mathbf{I}$ (identity matrix) $\in \mathbb{R}^{n \times n}$, $\mathbf{v} \in \mathbb{R}^n$
- **Eigenvalue** ($\lambda$): $\text{det}(\mathbf{A} - \lambda \mathbf{I}) = 0$
- **Eigenvector** ($\mathbf{v}$): $\mathbf{A} \mathbf{v} = \lambda \mathbf{v} \iff (\mathbf{A} - \lambda \mathbf{I}) \mathbf{v} = 0$
- **Normalize vector**: $\frac{\mathbf{v}}{\|\mathbf{v}\|}$, $v_i = \frac{v_i}{\sqrt{\sum_{i=1}^{n} v_i^2}}$

Cho trước $\mathbf{A} = \begin{bmatrix}
0.9 & 0.2 \\
0.1 & 0.8
\end{bmatrix}$

Tìm Eigenvector ($\mathbf{v}$) đã được normalize và eigenvalue $\lambda$ của $\mathbf{A}$.

Dựa vào công thức ở trên, hãy hoàn thiện hàm `compute_eigenvalues_eigenvectors()` sử dụng thư viện numpy:

In [11]:
import numpy as np

def compute_eigenvalues_eigenvectors(matrix):
  A = np.array(matrix)
  eigenvalues = np.linalg.eigvals(A)
  eigenvectors = np.linalg.eig(A)

  return eigenvalues, eigenvectors

In [12]:
A = [[0.9, 0.2], [0.1, 0.8]]
compute_eigenvalues_eigenvectors(A)

(array([1. , 0.7]),
 EigResult(eigenvalues=array([1. , 0.7]), eigenvectors=array([[ 0.89442719, -0.70710678],
        [ 0.4472136 ,  0.70710678]])))

## 3. Cosine Similarity:

### 3.1 Cosine Similarity

- **Data (vector x, y)**: $\mathbf{x} = \{x_1, ..., x_N\}$, $\mathbf{y} = \{y_1, ..., y_N\}$
- **Cosine Similarity**: $\text{cs}(\mathbf{x}, \mathbf{y}) = \frac{\mathbf{x} \cdot \mathbf{y}}{\|\mathbf{x}\| \|\mathbf{y}\|} = \frac{\sum_{i=1}^N x_i y_i}{\sqrt{\sum_{i=1}^N x_i^2} \sqrt{\sum_{i=1}^N y_i^2}}$

Cho trước $\mathbf{x} = \begin{bmatrix} 1 \\ 2 \\ 3 \\ 4 \end{bmatrix}$ và $\mathbf{y} = \begin{bmatrix} 1 \\ 0 \\ 1 \\ 0 \end{bmatrix}$, tìm Cosine similarity $\text{cs}(\mathbf{x}, \mathbf{y})$.

Dựa vào công thức ở trên, hãy hoàn thiện hàm `compute_cosine()` sử dụng thư viện numpy:

In [13]:
def compute_cosine(v1, v2):
    # *********** Your code here ***********
    x = np.array(v1)
    y = np.array(v2)
    cos_sim = np.dot(x, y) / np.dot(np.linalg.norm(x), np.linalg.norm(y))

    return cos_sim

In [14]:
x = [1, 2, 3, 4]
y = [1, 0, 1, 0]
compute_cosine(x, y)

0.5163977794943222